#!/usr/bin/env bash
#
# Axis 8: switching the palette reaches every foreign program.
#
# The project's central promise is "change one colour scheme and everything
# follows". Everything else proves half of it — tests/all-palettes.sh proves each
# palette resolves to a full token set, tests/reachable.sh proves each generated
# file is pointed at by its owner. Neither asks the question a user asks: I
# picked a different scheme, did it arrive?
#
# ⚠️ THE CONTROL IS THE POINT, and it is why this is not just "diff everything".
# A test that only asserts "these files changed" passes just as happily if the
# renderer wrote a timestamp into all sixteen, or truncated the lot. So two
# lists, and both are checked:
#
#   MUST CHANGE     files that carry colours. A palette switch that leaves one
#                   alone is a program still wearing the old scheme.
#   MUST NOT CHANGE files that carry none. config.kdl is the important one:
#                   niri's colours live in colors.kdl, which config.kdl
#                   INCLUDES, and that separation is why a palette switch does
#                   not have to touch the compositor's structure. If it ever
#                   starts changing, the include has stopped doing its job and
#                   every palette switch is costing a full niri reload.
#
# ⚠️ TWO DARK PALETTES, deliberately. Between a dark and a light one the GTK
# settings.ini files change as well (gtk-application-prefer-dark-theme), which
# would make them look like colour files and hide a real regression in them.
set -uo pipefail
cd "$(dirname "$0")/.." || exit 2

command -v qs >/dev/null || { echo "quickshell (qs) not installed"; exit 2; }

fail=0
tmp="$(mktemp -d)" || exit 2
trap 'rm -rf "$tmp"' EXIT
mkdir -p "$tmp/buchhwin" "$tmp/niri" "$tmp/environment.d" "$tmp/share" "$tmp/home" \
         "$tmp/gtk-3.0" "$tmp/gtk-4.0" "$tmp/kitty" "$tmp/qt6ct/colors" \
         "$tmp/btop/themes" "$tmp/alacritty" "$tmp/tmux" "$tmp/bat/themes" \
         "$tmp/git" "$tmp/lazygit" "$tmp/Code/User"

# Colours. Every one of these is written from the 26 palette names.
MUST_CHANGE=(
    "gtk-3.0/gtk.css"
    "gtk-4.0/gtk.css"
    "kitty/theme.conf"
    "qt6ct/colors/buchhwin.conf"
    "btop/themes/buchhwin.theme"
    "alacritty/buchhwin.toml"
    "tmux/buchhwin.conf"
    "bat/themes/buchhwin.tmTheme"
    "git/buchhwin-delta.gitconfig"
    "lazygit/buchhwin.yml"
    "niri/colors.kdl"
)
# No colours in them — each listed with its reason, so a change that moves a
# file between the lists has to say why rather than just editing an array.
MUST_NOT_CHANGE=(
    "niri/config.kdl"           # colours are in colors.kdl, which this includes
    "gtk-3.0/settings.ini"      # font and icon theme; dark-vs-light is the only mover
    "gtk-4.0/settings.ini"      # same
    "Code/User/settings.json"   # names the theme; the theme file carries the colours
)

render() {   # $1 = palette
    printf '{"version":1,"theme":{"palette":"%s","accent":"blue"}}\n' "$1" \
        > "$tmp/buchhwin/shell.json"
    for tool in render niri; do
        HOME="$tmp/home" XDG_CONFIG_HOME="$tmp" XDG_DATA_HOME="$tmp/share" \
            BUCHHWIN_TOOL="$tool" QT_QPA_PLATFORM=offscreen \
            timeout 60 qs -p shell >/dev/null 2>&1
    done
}

# ⚠️ THE PROVENANCE LINE IS MASKED BEFORE ANYTHING IS COMPARED, and doing that
# makes the test STRICTER rather than looser. Every generated file opens with
# "Generated by buchhwin from palette '<name>'", so a file whose colours had
# stopped updating would still differ on that one line and would pass the
# must-change half while being completely stale. Masking it means "this file
# changed" can only mean "its contents changed".
#
# Found by the must-not-change half: both GTK settings.ini files differed
# between two dark palettes, and the entire difference was that header. Nothing
# functional in them depends on the palette — gtk-theme-name is adw-gtk3-dark
# either way — so the honest fix was a better comparison, not a longer list.
fingerprint() {   # $1 = path
    sed "s/from palette '[^']*'/from palette 'X'/" "$1" 2>/dev/null | cksum
}

snap() {     # $1 = destination file
    : > "$1"
    local f
    for f in "${MUST_CHANGE[@]}" "${MUST_NOT_CHANGE[@]}"; do
        if [[ -f "$tmp/$f" ]]; then
            printf '%s %s\n' "$f" "$(fingerprint "$tmp/$f")" >> "$1"
        else
            printf '%s missing\n' "$f" >> "$1"
        fi
    done
    # ⚠️ The VS Code extension lives under HOME, not XDG_CONFIG_HOME — VS Code
    # looks in ~/.vscode/extensions whatever the XDG variables say, so the two
    # halves of this snapshot legitimately read from different roots.
    local vs="$tmp/home/.vscode/extensions/buchhwin-theme/themes/buchhwin-color-theme.json"
    if [[ -f "$vs" ]]; then
        printf 'vscode-theme %s\n' "$(fingerprint "$vs")" >> "$1"
    else
        printf 'vscode-theme missing\n' >> "$1"
    fi
}

printf '  %-40s ' "everforest-dark renders"
render everforest-dark
snap "$tmp/a"
if grep -q missing "$tmp/a"; then
    printf '\033[38;5;203mnot every file was written\033[0m\n'
    grep missing "$tmp/a" | sed 's/^/      /'
    exit 1
fi
printf '\033[38;5;114mok\033[0m\n'

printf '  %-40s ' "switch to dracula"
render dracula
snap "$tmp/b"
if grep -q missing "$tmp/b"; then
    printf '\033[38;5;203ma file disappeared on the switch\033[0m\n'
    grep missing "$tmp/b" | sed 's/^/      /'; exit 1
fi
printf '\033[38;5;114mok\033[0m\n'

changed() {  # $1 = key — true when the two snapshots differ for it
    [[ "$(grep -m1 "^$1 " "$tmp/a")" != "$(grep -m1 "^$1 " "$tmp/b")" ]]
}

stale=""
for f in "${MUST_CHANGE[@]}" vscode-theme; do
    changed "$f" || stale+=" $f"
done
printf '  %-40s ' "every colour file followed"
if [[ -z "$stale" ]]; then
    printf '\033[38;5;114mok\033[0m  %d files\n' "$(( ${#MUST_CHANGE[@]} + 1 ))"
else
    printf '\033[38;5;203mstill on the old palette:%s\033[0m\n' "$stale"; fail=1
fi

moved=""
for f in "${MUST_NOT_CHANGE[@]}"; do
    changed "$f" && moved+=" $f"
done
printf '  %-40s ' "and nothing else moved"
if [[ -z "$moved" ]]; then
    printf '\033[38;5;114mok\033[0m\n'
else
    printf '\033[38;5;203mchanged and should not have:%s\033[0m\n' "$moved"
    printf '      config.kdl changing means the colors.kdl include has stopped\n'
    printf '      carrying the colours, so every palette switch now costs a\n'
    printf '      full niri reload.\n'
    fail=1
fi

# ⚠️ AND BACK AGAIN, because "it changed" is not "it changed to the right
# thing". Rendering the first palette a second time must reproduce the first
# snapshot exactly. If it does not, something in the output is not derived from
# the palette at all — a timestamp, a path, an unordered map — and every
# comparison above was measuring that instead of the colours.
printf '  %-40s ' "switching back reproduces it exactly"
render everforest-dark
snap "$tmp/c"
if diff -q "$tmp/a" "$tmp/c" >/dev/null 2>&1; then
    printf '\033[38;5;114mok\033[0m\n'
else
    printf '\033[38;5;203mnot reproducible\033[0m\n'
    diff "$tmp/a" "$tmp/c" | head -8 | sed 's/^/      /'
    fail=1
fi

exit $fail
