# Phase: base — the packages nothing else works without.
phase_base() {
    section "Base system"
    mapfile -t pkgs < <(read_list dnf-core.txt)
    step "${#pkgs[@]} packages"
    dnf_install weak "${pkgs[@]}" || die "base packages failed"
    ok "base system"

    # `dnf i` as well as `dnf install`, and under sudo too.
    #
    # dnf5 already ships `in` for install and `if` for info; this adds the
    # single letter. It goes in a SYSTEM directory on purpose — a shell alias
    # would not survive `sudo`, which runs the real binary, and this is a
    # package manager: the sudo form is the one that matters.
    #
    # ⚠️ Two things measured rather than assumed, because both failed first:
    # the drop-in directory is /etc/dnf/dnf5-aliases.d (NOT the empty
    # /etc/dnf/aliases.d that also exists), and the file must end in .conf —
    # a .toml is ignored without a word, which looks exactly like a wrong alias.
    if [[ -d /usr/share/dnf5/aliases.d ]]; then
        sudo mkdir -p /etc/dnf/dnf5-aliases.d
        sudo tee /etc/dnf/dnf5-aliases.d/buchhwin.conf >/dev/null <<'EOF'
# Generated by buchhwin. `dnf i` alongside dnf5's own `in` and `if`.
version = '1.0'

['i']
type = 'command'
attached_command = 'install'
descr = "Alias for 'install'"
EOF
        ok "dnf i works as dnf install (sudo too)"
    fi
}
