# shellcheck shell=bash
# Sourced by install.sh, never executed — so there is no shebang, and the
# directive above is how shellcheck is told which shell to assume.
# Phase: services — four units, down from the previous project's thirteen.
# Everything else that used to need a daemon is inside the shell.
phase_services() {
    section "Services"
    local u="$CONFIG_HOME/systemd/user"
    mkdir -p "$u"

    # ⚠️ SYSTEM SERVICES THE SHELL ALREADY HAS AN INTERFACE FOR. Each of these
    # was found by comparing against the predecessor, and each is the same
    # shape: a panel in the shell, and nothing running behind it.
    #
    #   bluetooth  services/Bt.qml and ui/quick/BluetoothList.qml have shipped
    #              since M4. Fedora Workstation starts bluez; Server does not.
    #   cups       costs nothing until the first print job, and its absence is
    #              only discovered when you need to print.
    #   udisks2    mounting a USB stick without a password. ⚠️ NOT automount:
    #              that needs a client sitting in the session, and the two that
    #              exist are GTK or Python, both of which this project does not
    #              take. The file manager mounts on click, which is the honest
    #              half — said here rather than left to be discovered.
    #   avahi      .local names. Without it `ssh nas.local` does not resolve on
    #              a network where everything else finds it.
    #   oomd       kills the one runaway process instead of letting the machine
    #              swap itself to a standstill. On a laptop that is the
    #              difference between a lost tab and a lost session.
    #   tuned-ppd  Fedora's power profiles since F41 — it replaced
    #              power-profiles-daemon, and the desktop's own power menu talks
    #              to that D-Bus name. Not tlp: the two collide, and which one
    #              wins is not decided here but measured on the laptop (M10).
    step "system services"
    for unit in bluetooth.service cups.socket udisks2.service avahi-daemon.service \
                systemd-oomd.service tuned-ppd.service; do
        if systemctl list-unit-files "$unit" >/dev/null 2>&1 \
           && ! systemctl is-enabled --quiet "$unit" 2>/dev/null; then
            sudo systemctl enable --now "$unit" >/dev/null 2>&1 \
                && ok "$unit enabled" || warn "$unit could not be enabled"
        fi
    done

    # ⚠️ THE KEYRING IS NOT UNLOCKED AT LOGIN WITHOUT THIS, and the symptom is a
    # second password prompt after every single login — plus network and cloud
    # mounts that stay disconnected. gnome-keyring is installed
    # (packages/dnf-desktop.txt) and was never wired into PAM; the predecessor
    # did exactly this and the rewrite left it behind.
    #
    # Idempotent, and it takes a backup: editing a PAM file badly is how a
    # machine stops accepting logins at all.
    if [[ -f /etc/pam.d/sddm ]] && ! grep -q pam_gnome_keyring /etc/pam.d/sddm; then
        sudo cp -n /etc/pam.d/sddm /etc/pam.d/sddm.buchhwin-backup
        printf 'auth     optional pam_gnome_keyring.so\nsession  optional pam_gnome_keyring.so auto_start\n' \
            | sudo tee -a /etc/pam.d/sddm >/dev/null
        ok "keyring unlocks with the login"
    fi

    # ⚠️ THE JOURNAL GROWS TO 10 % OF THE PARTITION BY DEFAULT. The predecessor
    # capped it after measuring 3.9 GB on one machine; the rewrite did not carry
    # the file across. A laptop with a small root filesystem notices.
    if [[ ! -f /etc/systemd/journald.conf.d/buchhwin.conf ]]; then
        sudo mkdir -p /etc/systemd/journald.conf.d
        sudo tee /etc/systemd/journald.conf.d/buchhwin.conf >/dev/null <<'JOURNAL'
# Generated by buchhwin. Without a cap the journal takes 10% of the partition.
[Journal]
SystemMaxUse=500M
SystemMaxFileSize=50M
MaxRetentionSec=1month
JOURNAL
        ok "journal capped at 500M"
    fi

    # ⚠️ THE KEYBOARD LAYOUT REACHES niri AND NOTHING ELSE. `input.keyboard.layout`
    # goes into the generated niri config, which is the session — but the LOGIN
    # SCREEN and the TTY are not the session, and the login screen is where you
    # type your password FIRST. A German user on a US-layout greeter types the
    # password wrong before the desktop has started.
    if command -v localectl >/dev/null; then
        # The layout the session will use, read from the one file that owns
        # it. Defaulting to nothing rather than to a guess: a wrong system
        # keymap is worse than the one Fedora already chose.
        local kb=""
        if [[ -f "$CONFIG_HOME/buchhwin/shell.json" ]]; then
            kb="$(python3 -c 'import json,sys
try:
    c=json.load(open(sys.argv[1]))
    print(c.get("input",{}).get("keyboard",{}).get("layout",""))
except Exception:
    print("")' "$CONFIG_HOME/buchhwin/shell.json" 2>/dev/null)"
        fi
        [[ -n "$kb" ]] || kb="de"
        if [[ -n "$kb" ]] && [[ "$(localectl status 2>/dev/null | awk -F: '/X11 Layout/{gsub(/ /,"",$2);print $2}')" != "$kb" ]]; then
            sudo localectl set-x11-keymap "$kb" >/dev/null 2>&1 \
                && ok "greeter and TTY use the $kb layout" \
                || warn "could not set the system keymap"
        fi
    fi

    cat > "$u/buchhwin-shell.service" <<UNIT
[Unit]
Description=buchhwin shell (quickshell)
PartOf=graphical-session.target
After=graphical-session.target
# ⚠️ THESE THREE BELONG IN [Unit] AND WERE IN [Service], WHERE SYSTEMD IGNORES
# THEM. Measured on his laptop, in the journal at every start:
#   buchhwin-shell.service:27: Unknown key 'StartLimitIntervalSec' in section
#   [Service], ignoring.   ... and the same for 'OnFailure'.
# So the restart brake was OFF — a shell that crashes on startup would have
# looped for ever instead of stopping after five tries — and
# buchhwin-shell-failed.service, the terminal window whose whole job is to
# explain why the shell died, could NEVER fire. A unit with a handler nothing
# can reach is the same fault this project keeps finding one layer up.
StartLimitIntervalSec=60
StartLimitBurst=5
OnFailure=buchhwin-shell-failed.service

[Service]
Type=simple
# Quickshell never removes the instance directory a run leaves behind, and they
# live in a tmpfs. 407 of them, 15 MB of RAM, had accumulated on the test
# machine. Pruning here rather than on shutdown is deliberate: at this moment
# the previous instance is already gone, so "qs list" names only what is really
# alive. The leading minus means a failed cleanup can never stop the desktop
# from starting.
#
# NOTE for whoever edits this comment: it is inside an UNQUOTED heredoc, so
# backticks here are command substitution and would be RUN at install time.
# This very line used to say "qs list" in backticks and the installer executed
# it, printing "sh: -: command not found" and writing the empty result into the
# unit. Quotes here, never backticks -- and the delimiter stays unquoted
# because the ExecStartPre line below needs $REPO_DIR expanded.
ExecStartPre=-$REPO_DIR/bin/bhctl prune
ExecStart=/usr/bin/qs -c buchhwin
# A shell that dies takes the bar, the notch and every menu with it, so it
# comes back on its own — but not in a tight loop that would hide the cause.
Restart=always
RestartSec=2

[Install]
WantedBy=graphical-session.target
UNIT

    # When the shell is dead, notify-send is useless: the notification server
    # IS the dead thing. A terminal always works.
    cat > "$u/buchhwin-shell-failed.service" <<UNIT
[Unit]
Description=Explain why the buchhwin shell stopped

[Service]
Type=oneshot
ExecStart=/usr/bin/kitty --title "buchhwin shell failed" -- \
    sh -c "journalctl --user -u buchhwin-shell -n 60 --no-pager; echo; echo 'Press enter to close.'; read _"
UNIT

    cat > "$u/buchhwin-clipboard.service" <<UNIT
[Unit]
Description=Clipboard history (cliphist)
PartOf=graphical-session.target
After=graphical-session.target

[Service]
Type=simple
ExecStart=/bin/sh -c '/usr/bin/wl-paste --type text --watch /usr/bin/cliphist store'
Restart=always

[Install]
WantedBy=graphical-session.target
UNIT

    systemctl --user daemon-reload 2>/dev/null || true
    systemctl --user enable buchhwin-shell.service buchhwin-clipboard.service >/dev/null 2>&1 \
        || warn "could not enable the user services (no session yet is normal)"
    ok "3 user units written and enabled"
}
