// The niri config generator: shell.json -> ~/.config/niri/config.kdl.
//
//   BUCHHWIN_TOOL=niri QT_QPA_PLATFORM=offscreen qs -p shell
//
// config.kdl is an OUTPUT. Editing it by hand edits something that is
// overwritten on the next settings change, which is why the file says so in
// its own header.
//
// Two files are written, and the second one is not an afterthought:
//
//   ~/.config/niri/config.kdl            everything except colours
//   ~/.config/environment.d/50-buchhwin.conf   the same variables, for systemd
//
// niri's own `environment {}` block does NOT reach the systemd and D-Bus
// activation environment. Our shell runs as a systemd user unit and the
// programs it launches are its children, so they would never see a variable
// set only in config.kdl. Anything that has to reach an app — Qt decoration
// off, Firefox on Wayland — therefore goes in BOTH places. Skipping the
// environment.d half is how "no window buttons" becomes a claim that is not
// true in practice.
//
// Colours are deliberately NOT here. tools/render.qml writes colors.kdl and
// this file includes it, so changing the palette never rewrites the keybinds.

import QtQuick
import Quickshell
import Quickshell.Io
import "../theme"
import "../config"
import "../common"

Scope {
    id: root

    readonly property string home: Quickshell.env("HOME")
    readonly property string cfg: Quickshell.env("XDG_CONFIG_HOME") || (home + "/.config")

    property string report: ""
    property int written: 0
    property int unchanged: 0

    function note(s) { report += s + "\n"; log.setText(report) }

    // Write only on a real change.
    //
    // niri live-reloads on every write of config.kdl AND of every file it
    // includes. Rewriting an identical file therefore costs a full compositor
    // reload for nothing — and it turns "a second install run changes no file"
    // from a claim into something that is actually true.
    function write(view, path, text, label) {
        view.path = path
        // The FileViews below set blockLoading: true, so this read is
        // synchronous. Without it `text()` returns "" — the load has only just
        // been queued — every file looks changed, and the whole point of
        // comparing is lost. That is not a theory: the first version of this
        // function reported "2 written" on a run that changed nothing.
        var old = view.text()
        if (old === text) {
            unchanged++
            note("  same   " + label)
            return
        }
        view.setText(text)
        written++
        note("  wrote  " + label + "  ->  " + path)
    }

    // ------------------------------------------------------------- KDL basics
    // KDL needs a newline or a `;` to end a node. `layout { gaps 16 }` on one
    // line is a parse error, so anything emitted inline gets its semicolon.
    function q(s) { return "\"" + String(s).replace(/\\/g, "\\\\").replace(/"/g, "\\\"") + "\"" }

    // niri's libinput flags REJECT `false` — `natural-scroll false` is a hard
    // error, unlike most other niri flags which accept it. So a device flag is
    // written when on and omitted when off. This asymmetry is the single most
    // likely place for a generator to produce an invalid config.
    function flag(name, on, indent) { return on ? indent + name + "\n" : "" }

    function argList(list) {
        var out = ""
        for (var i = 0; i < list.length; i++)
            out += " " + q(list[i])
        return out
    }

    readonly property string header:
        "// Generated by buchhwin from ~/.config/buchhwin/shell.json\n" +
        "//\n" +
        "// Do not edit: this file is rewritten whenever a setting changes.\n" +
        "// Change the setting instead, then run `bhctl niri apply`.\n" +
        "//\n" +
        "// Colours live in colors.kdl, included below — a palette change does\n" +
        "// not touch anything here.\n"

    // ------------------------------------------------------------------ input
    function inputSection() {
        var k = Config.input.keyboard
        var t = Config.input.touchpad
        var m = Config.input.mouse
        var s = "input {\n"
        s += "    keyboard {\n"
        s += "        xkb {\n"
        s += "            layout " + q(k.layout) + "\n"
        if (String(k.variant).length) s += "            variant " + q(k.variant) + "\n"
        if (String(k.options).length) s += "            options " + q(k.options) + "\n"
        s += "        }\n"
        s += "        repeat-delay " + k.repeatDelay + "\n"
        s += "        repeat-rate " + k.repeatRate + "\n"
        s += "    }\n"
        s += "    touchpad {\n"
        s += flag("tap", t.tap, "        ")
        s += flag("dwt", t.dwt, "        ")
        s += flag("natural-scroll", t.naturalScroll, "        ")
        s += flag("middle-emulation", t.middleEmulation, "        ")
        s += "        accel-speed " + t.accelSpeed + "\n"
        s += "        accel-profile " + q(t.accelProfile) + "\n"
        s += "        scroll-method " + q(t.scrollMethod) + "\n"
        s += "        click-method " + q(t.clickMethod) + "\n"
        s += "    }\n"
        s += "    mouse {\n"
        s += flag("natural-scroll", m.naturalScroll, "        ")
        s += "        accel-speed " + m.accelSpeed + "\n"
        s += "        accel-profile " + q(m.accelProfile) + "\n"
        s += "    }\n"
        s += flag("focus-follows-mouse", Config.input.focusFollowsMouse, "    ")
        s += flag("warp-mouse-to-focus", Config.input.warpMouseToFocus, "    ")
        s += "    mod-key " + q(Config.keys.mod) + "\n"
        s += "}\n"
        return s
    }

    // ---------------------------------------------------------------- outputs
    function outputsSection() {
        var outs = Config.outputs
        if (!outs || !outs.length)
            return "// No output overrides: niri's own detection is better than a\n" +
                   "// guess, and this file is per-machine anyway.\n"
        var s = ""
        for (var i = 0; i < outs.length; i++) {
            var o = outs[i]
            s += "output " + q(o.name) + " {\n"
            if (o.mode) s += "    mode " + q(o.mode) + "\n"
            if (o.scale !== undefined && o.scale !== null) s += "    scale " + o.scale + "\n"
            if (o.transform) s += "    transform " + q(o.transform) + "\n"
            if (o.x !== undefined && o.y !== undefined)
                s += "    position x=" + o.x + " y=" + o.y + "\n"
            s += flag("variable-refresh-rate", o.vrr === true, "    ")
            s += "}\n"
        }
        return s
    }

    // ----------------------------------------------------------------- layout
    function layoutSection() {
        var L = Config.look
        var s = "layout {\n"
        s += "    gaps " + L.gapsOut + "\n"
        s += "    center-focused-column \"never\"\n"
        // on/off belongs HERE and nowhere else. In an INCLUDED file a bare
        // `border {}` does nothing, while in the main config it means "on" —
        // so colors.kdl carries colours only and never decides visibility.
        s += "    border {\n"
        s += (L.borderWidth > 0 ? "        on\n        width " + L.borderWidth + "\n"
                                : "        off\n")
        s += "    }\n"
        s += "    focus-ring {\n        off\n    }\n"
        s += "    shadow {\n"
        s += (Theme.shadows ? "        on\n" : "        off\n")
        s += "    }\n"
        s += "    struts {\n"
        s += "        left " + L.gapsIn + "\n"
        s += "        right " + L.gapsIn + "\n"
        s += "        top 0\n"
        s += "        bottom 0\n"
        s += "    }\n"
        s += "}\n"
        return s
    }

    // ------------------------------------------------------------ environment
    // Kept in step with environmentD() below — the same list twice, on purpose,
    // because the two are read by different things.
    readonly property var envVars: [
        // Qt draws no title bar of its own; the compositor decides.
        ["QT_QPA_PLATFORM", "wayland"],
        ["QT_WAYLAND_DISABLE_WINDOWDECORATION", "1"],
        ["QT_QPA_PLATFORMTHEME", "qt6ct"],
        ["MOZ_ENABLE_WAYLAND", "1"],
        ["ELECTRON_OZONE_PLATFORM_HINT", "wayland"],
        ["XDG_SESSION_TYPE", "wayland"],
        ["_JAVA_AWT_WM_NONREPARENTING", "1"]
        // ⚠️ GDK_BACKEND is deliberately absent. niri's own documentation:
        // "Do not set the GDK_BACKEND environment variable globally as this
        // will break the screencast portal." GTK apps pick Wayland on their
        // own here; forcing it costs screen sharing.
    ]

    function environmentSection() {
        var s = "environment {\n"
        for (var i = 0; i < envVars.length; i++)
            s += "    " + envVars[i][0] + " " + q(envVars[i][1]) + "\n"
        s += "}\n"
        return s
    }

    function environmentD() {
        var s = "# Generated by buchhwin. Do not edit.\n" +
                "#\n" +
                "# The same variables as the environment{} block in niri's config.kdl,\n" +
                "# because that block does NOT reach the systemd/D-Bus activation\n" +
                "# environment — and our shell, and everything it launches, lives there.\n"
        for (var i = 0; i < envVars.length; i++)
            s += envVars[i][0] + "=" + envVars[i][1] + "\n"
        return s
    }

    // ------------------------------------------------------------------- misc
    function miscSection() {
        var s = ""
        s += Config.windows.noCsd ? "prefer-no-csd\n" : ""
        s += "screenshot-path " + q("~/Bilder/Screenshots/%Y-%m-%d %H-%M-%S.png") + "\n"
        s += "\ncursor {\n    hide-when-typing\n}\n"
        s += "\nhotkey-overlay {\n    skip-at-startup\n}\n"
        return s
    }

    function blurSection() {
        // look.profile "minimal" is the one switch that turns the expensive
        // things off everywhere at once, rather than a setting per effect.
        if (Config.look.profile === "minimal" || !Config.look.blur)
            return "blur {\n    off\n}\n"
        return "blur {\n    passes " + Config.look.blurPasses + "\n}\n"
    }

    function workspacesSection() {
        var w = Config.workspaces
        var s = ""
        for (var i = 0; i < w.length; i++)
            s += "workspace " + q(w[i]) + "\n"
        return s
    }

    // ------------------------------------------------------------- rules
    function windowRules() {
        var L = Config.look
        var s = "window-rule {\n"
        s += "    geometry-corner-radius " + L.rounding + "\n"
        s += "    clip-to-geometry true\n"
        s += "}\n"
        if (L.opacityInactive < 1.0) {
            s += "\nwindow-rule {\n"
            s += "    match is-active=false\n"
            s += "    opacity " + L.opacityInactive + "\n"
            s += "}\n"
        }
        var fl = Config.windows.floating
        for (var i = 0; i < fl.length; i++) {
            s += "\nwindow-rule {\n"
            s += "    match app-id=" + q("^" + fl[i] + "$") + "\n"
            s += "    open-floating true\n"
            s += "}\n"
        }
        var bl = Config.windows.blockFromScreencast
        for (var j = 0; j < bl.length; j++) {
            s += "\nwindow-rule {\n"
            s += "    match app-id=" + q("^" + bl[j] + "$") + "\n"
            s += "    block-out-from \"screencast\"\n"
            s += "}\n"
        }
        return s
    }

    function layerRules() {
        // The namespace is a public interface: the shell's layer surfaces are
        // named buchhwin-* and these rules match them. Renaming one later
        // silently drops its blur, so they do not get renamed.
        if (Config.look.profile === "minimal" || !Config.look.blur)
            return "// Blur off (look.profile minimal): no layer effects.\n"
        var s = "layer-rule {\n"
        s += "    match namespace=" + q("^buchhwin-notch$") + "\n"
        s += "    background-effect {\n"
        s += "        blur true\n"
        s += "    }\n"
        s += "}\n"
        s += "\nlayer-rule {\n"
        s += "    match namespace=" + q("^buchhwin-bar$") + "\n"
        s += "    background-effect {\n"
        s += "        blur true\n"
        s += "    }\n"
        s += "}\n"
        return s
    }

    // ------------------------------------------------------------------ binds
    // Actions that take a bare (unquoted) number rather than a string.
    readonly property var numericActions: ["focus-workspace", "move-window-to-workspace",
                                           "move-column-to-workspace"]

    function bindLine(b) {
        var key = String(b.key)
        var action = String(b.action)
        var arg = b.arg === undefined || b.arg === null ? "" : String(b.arg)

        var body = ""
        if (action === "spawn") {
            // One string per argument. `spawn "kitty -e fish"` makes niri look
            // for a binary called "kitty -e fish"; the error message does not
            // mention the real cause, so this is worth getting right once.
            var argv = Config.program(arg)
            if (!argv.length)
                return ""   // no program configured: drop the key rather than
                            // bind it to something that quietly does nothing
            body = "spawn" + argList(argv)
        } else if (action === "spawn-sh") {
            if (!arg.length) return ""
            body = "spawn-sh " + q(arg)
        } else if (arg.length) {
            var numeric = numericActions.indexOf(action) >= 0 && /^[0-9]+$/.test(arg)
            body = action + " " + (numeric ? arg : q(arg))
        } else {
            body = action
        }

        var props = ""
        if (b.allowWhenLocked === true) props += " allow-when-locked=true"
        if (b.repeat === false) props += " repeat=false"
        if (typeof b.cooldownMs === "number") props += " cooldown-ms=" + b.cooldownMs
        if (b.desc) props += " hotkey-overlay-title=" + q(b.desc)

        return "    " + key + props + " { " + body + "; }\n"
    }

    function bindsSection() {
        var s = "binds {\n"
        var binds = Config.keys.binds
        var seen = ({})
        var dropped = 0
        for (var i = 0; i < binds.length; i++) {
            var b = binds[i]
            // A duplicate key is a hard parse error in niri, and a config that
            // does not load means a desktop with no keys at all. Catch it here,
            // where we can say which key, instead of there.
            if (seen[b.key]) {
                note("  ⚠ duplicate key dropped: " + b.key)
                dropped++
                continue
            }
            var line = bindLine(b)
            if (!line.length) { dropped++; continue }
            seen[b.key] = true
            s += line
        }
        // Workspace switching, generated rather than typed out ten times.
        for (var n = 1; n <= 9; n++) {
            s += "    Mod+" + n + " { focus-workspace " + n + "; }\n"
            s += "    Mod+Shift+" + n + " { move-window-to-workspace " + n + "; }\n"
        }
        s += "}\n"
        if (dropped)
            note("  " + dropped + " binding(s) skipped (no program configured or duplicate)")
        return s
    }

    // -------------------------------------------------------------- autostart
    function autostartSection() {
        // NOT the shell and NOT the clipboard watcher. Both are systemd user
        // units bound to graphical-session.target already; listing them here
        // would start a second copy of each. This is the exact mistake in
        // Fedora's shipped niri config, which spawns waybar at startup.
        var a = Config.autostart
        if (!a.length)
            return "// Nothing to spawn: the shell and the clipboard watcher are\n" +
                   "// systemd user units, not startup commands. Adding them here\n" +
                   "// would run a second copy of each.\n"
        // ⚠️ NOT `spawn-sh` — that is the name of a BIND action. At the top
        // level the node is `spawn-sh-at-startup`, and niri rejects the other
        // spelling outright ("unexpected node `spawn-sh`"), which means no
        // config at all and therefore a desktop with no keybindings.
        var s = ""
        for (var i = 0; i < a.length; i++)
            s += "spawn-sh-at-startup " + q(a[i]) + "\n"
        return s
    }

    // ------------------------------------------------------------------ build
    function buildConfig() {
        var parts = []
        parts.push(header)
        parts.push(inputSection())
        parts.push(outputsSection())
        parts.push(layoutSection())
        // AFTER layout, on purpose: an include overrides what came before it,
        // so the colours have to be read after the structure that they tint.
        parts.push("// Colours, written by tools/render.qml on every palette change.\n" +
                   "// optional=true: a fresh checkout has no colours yet and that must\n" +
                   "// not stop niri from starting.\n" +
                   "include optional=true " + q("~/.config/niri/colors.kdl") + "\n")
        parts.push(miscSection())
        parts.push(environmentSection())
        parts.push(blurSection())
        parts.push(workspacesSection())
        parts.push(windowRules())
        parts.push(layerRules())
        parts.push(bindsSection())
        parts.push(autostartSection())
        return parts.join("\n")
    }

    // blockLoading so that write() can compare against what is already on disk
    // in the same statement. printErrors off: "the file is not there yet" is
    // the normal case on a first run, not a fault worth shouting about.
    FileView { id: fConfig; blockLoading: true; printErrors: false }
    FileView { id: fEnv; blockLoading: true; printErrors: false }
    FileView { id: log; path: "/tmp/buchhwin-niri.log" }

    WaitFor {
        condition: Config.settled

        onTimedOut: {
            note("buchhwin niri — ABORT: the configuration never settled")
            Qt.callLater(Qt.quit)
        }

        onReady: {
            note("buchhwin niri — generating from shell.json (version " + Config.version + ")")
            write(fConfig, root.cfg + "/niri/config.kdl", buildConfig(), "niri config")
            write(fEnv, root.cfg + "/environment.d/50-buchhwin.conf",
                  environmentD(), "environment.d")
            note("done: " + written + " written, " + unchanged + " unchanged")
            Qt.callLater(Qt.quit)
        }
    }
}
