// The niri config generator: shell.json -> ~/.config/niri/config.kdl.
//
//   BUCHHWIN_TOOL=niri QT_QPA_PLATFORM=offscreen qs -p shell
//
// config.kdl is an OUTPUT. Editing it by hand edits something that is
// overwritten on the next settings change, which is why the file says so in
// its own header.
//
// Two files are written, and the second one is not an afterthought:
//
//   ~/.config/niri/config.kdl            everything except colours
//   ~/.config/environment.d/50-buchhwin.conf   the same variables, for systemd
//
// niri's own `environment {}` block does NOT reach the systemd and D-Bus
// activation environment. Our shell runs as a systemd user unit and the
// programs it launches are its children, so they would never see a variable
// set only in config.kdl. Anything that has to reach an app — Qt decoration
// off, Firefox on Wayland — therefore goes in BOTH places. Skipping the
// environment.d half is how "no window buttons" becomes a claim that is not
// true in practice.
//
// Colours are deliberately NOT here. tools/render.qml writes colors.kdl and
// this file includes it, so changing the palette never rewrites the keybinds.

import QtQuick
import Quickshell
import Quickshell.Io
import "../theme"
import "../config"
import "../common"

Scope {
    id: root

    readonly property string home: Quickshell.env("HOME")
    readonly property string cfg: Quickshell.env("XDG_CONFIG_HOME") || (home + "/.config")

    property string report: ""
    property int written: 0
    property int unchanged: 0

    function note(s) { report += s + "\n"; log.setText(report) }

    // Write only on a real change.
    //
    // niri live-reloads on every write of config.kdl AND of every file it
    // includes. Rewriting an identical file therefore costs a full compositor
    // reload for nothing — and it turns "a second install run changes no file"
    // from a claim into something that is actually true.
    function write(view, path, text, label) {
        view.path = path
        // The FileViews below set blockLoading: true, so this read is
        // synchronous. Without it `text()` returns "" — the load has only just
        // been queued — every file looks changed, and the whole point of
        // comparing is lost. That is not a theory: the first version of this
        // function reported "2 written" on a run that changed nothing.
        var old = view.text()
        if (old === text) {
            unchanged++
            note("  same   " + label)
            return
        }
        view.setText(text)
        written++
        note("  wrote  " + label + "  ->  " + path)
    }

    // ------------------------------------------------------------- KDL basics
    // KDL needs a newline or a `;` to end a node. `layout { gaps 16 }` on one
    // line is a parse error, so anything emitted inline gets its semicolon.
    function q(s) { return "\"" + String(s).replace(/\\/g, "\\\\").replace(/"/g, "\\\"") + "\"" }

    // niri's libinput flags REJECT `false` — `natural-scroll false` is a hard
    // error, unlike most other niri flags which accept it. So a device flag is
    // written when on and omitted when off. This asymmetry is the single most
    // likely place for a generator to produce an invalid config.
    function flag(name, on, indent) { return on ? indent + name + "\n" : "" }

    function argList(list) {
        var out = ""
        for (var i = 0; i < list.length; i++)
            out += " " + q(list[i])
        return out
    }

    readonly property string header:
        "// Generated by buchhwin from ~/.config/buchhwin/shell.json\n" +
        "//\n" +
        "// Do not edit: this file is rewritten whenever a setting changes.\n" +
        "// Change the setting instead, then run `bhctl niri apply`.\n" +
        "//\n" +
        "// Colours live in colors.kdl, included below — a palette change does\n" +
        "// not touch anything here.\n"

    // ------------------------------------------------------------------ input
    function inputSection() {
        var k = Config.input.keyboard
        var t = Config.input.touchpad
        var m = Config.input.mouse
        var s = "input {\n"
        s += "    keyboard {\n"
        s += "        xkb {\n"
        s += "            layout " + q(k.layout) + "\n"
        if (String(k.variant).length) s += "            variant " + q(k.variant) + "\n"
        if (String(k.options).length) s += "            options " + q(k.options) + "\n"
        s += "        }\n"
        s += "        repeat-delay " + k.repeatDelay + "\n"
        s += "        repeat-rate " + k.repeatRate + "\n"
        s += "    }\n"
        s += "    touchpad {\n"
        s += flag("tap", t.tap, "        ")
        s += flag("dwt", t.dwt, "        ")
        s += flag("natural-scroll", t.naturalScroll, "        ")
        s += flag("middle-emulation", t.middleEmulation, "        ")
        s += "        accel-speed " + t.accelSpeed + "\n"
        s += "        accel-profile " + q(t.accelProfile) + "\n"
        s += "        scroll-method " + q(t.scrollMethod) + "\n"
        s += "        click-method " + q(t.clickMethod) + "\n"
        s += "    }\n"
        s += "    mouse {\n"
        s += flag("natural-scroll", m.naturalScroll, "        ")
        s += "        accel-speed " + m.accelSpeed + "\n"
        s += "        accel-profile " + q(m.accelProfile) + "\n"
        s += "    }\n"
        s += flag("focus-follows-mouse", Config.input.focusFollowsMouse, "    ")
        s += flag("warp-mouse-to-focus", Config.input.warpMouseToFocus, "    ")
        s += "    mod-key " + q(Config.keys.mod) + "\n"
        s += "}\n"
        return s
    }

    // ---------------------------------------------------------------- outputs
    function outputsSection() {
        var outs = Config.outputs
        if (!outs || !outs.length)
            return "// No output overrides: niri's own detection is better than a\n" +
                   "// guess, and this file is per-machine anyway.\n"
        var s = ""
        for (var i = 0; i < outs.length; i++) {
            var o = outs[i]
            s += "output " + q(o.name) + " {\n"
            if (o.mode) s += "    mode " + q(o.mode) + "\n"
            if (o.scale !== undefined && o.scale !== null) s += "    scale " + o.scale + "\n"
            if (o.transform) s += "    transform " + q(o.transform) + "\n"
            if (o.x !== undefined && o.y !== undefined)
                s += "    position x=" + o.x + " y=" + o.y + "\n"
            s += flag("variable-refresh-rate", o.vrr === true, "    ")
            s += "}\n"
        }
        return s
    }

    // ----------------------------------------------------------------- layout
    function layoutSection() {
        var L = Config.look
        var s = "layout {\n"
        s += "    gaps " + L.gapsOut + "\n"
        s += "    center-focused-column \"never\"\n"
        // on/off belongs HERE and nowhere else. In an INCLUDED file a bare
        // `border {}` does nothing, while in the main config it means "on" —
        // so colors.kdl carries colours only and never decides visibility.
        s += "    border {\n"
        s += (L.borderWidth > 0 ? "        on\n        width " + L.borderWidth + "\n"
                                : "        off\n")
        s += "    }\n"
        s += "    focus-ring {\n        off\n    }\n"
        s += "    shadow {\n"
        if (Theme.shadows) {
            s += "        on\n"
            // Same three numbers as our own surfaces, so a window and the notch
            // sit at the same apparent height above the wallpaper.
            s += "        softness " + L.shadowSoftness + "\n"
            s += "        spread " + L.shadowSpread + "\n"
            s += "        offset x=0 y=" + L.shadowOffsetY + "\n"
            // ⚠️ A SETTING NOW, AND IT DEFAULTS TO FALSE. niri's own reason for
            // true is that it cannot know a client's corner radius — but the
            // window rule below sets `clip-to-geometry true` with a radius, so
            // it does. And with `look.opacityApp` opening GTK windows up, true
            // means the shadow shows THROUGH them: measured on Nautilus, the
            // interior went from (66,50,35) to (40,32,25) while the shadow
            // beside the window stayed identical.
            s += "        draw-behind-window "
                 + (L.shadowBehindWindow ? "true" : "false") + "\n"
        } else {
            s += "        off\n"
        }
        s += "    }\n"
        s += "    struts {\n"
        s += "        left " + L.gapsIn + "\n"
        s += "        right " + L.gapsIn + "\n"
        s += "        top 0\n"
        s += "        bottom 0\n"
        s += "    }\n"
        s += "}\n"
        return s
    }

    // ------------------------------------------------------------ environment
    // Kept in step with environmentD() below — the same list twice, on purpose,
    // because the two are read by different things.
    readonly property var envVars: [
        // Qt draws no title bar of its own; the compositor decides.
        ["QT_QPA_PLATFORM", "wayland"],
        ["QT_WAYLAND_DISABLE_WINDOWDECORATION", "1"],
        ["QT_QPA_PLATFORMTHEME", "qt6ct"],
        ["MOZ_ENABLE_WAYLAND", "1"],
        ["ELECTRON_OZONE_PLATFORM_HINT", "wayland"],
        ["XDG_SESSION_TYPE", "wayland"],
        ["_JAVA_AWT_WM_NONREPARENTING", "1"],
        // ⚠️ THE ONE THEME POINTER THAT HAS TO BE AN ENVIRONMENT VARIABLE.
        // lazygit reads exactly one config file, and its --help names the only
        // way to add a second: "Comma separated list to custom config file(s)".
        // Every other program we theme has an include of some kind; this one
        // does not, so the pointer lives here instead of in a file of the
        // user's. Ours is LAST, so anything they set themselves still wins.
        ["LG_CONFIG_FILE", root.cfg + "/lazygit/config.yml," +
                           root.cfg + "/lazygit/buchhwin.yml"]
        // ⚠️ GDK_BACKEND is deliberately absent. niri's own documentation:
        // "Do not set the GDK_BACKEND environment variable globally as this
        // will break the screencast portal." GTK apps pick Wayland on their
        // own here; forcing it costs screen sharing.
    ]

    function environmentSection() {
        var s = "environment {\n"
        for (var i = 0; i < envVars.length; i++)
            s += "    " + envVars[i][0] + " " + q(envVars[i][1]) + "\n"
        s += "}\n"
        return s
    }

    function environmentD() {
        var s = "# Generated by buchhwin. Do not edit.\n" +
                "#\n" +
                "# The same variables as the environment{} block in niri's config.kdl,\n" +
                "# because that block does NOT reach the systemd/D-Bus activation\n" +
                "# environment — and our shell, and everything it launches, lives there.\n"
        for (var i = 0; i < envVars.length; i++)
            s += envVars[i][0] + "=" + envVars[i][1] + "\n"
        return s
    }

    // ------------------------------------------------------------------- misc
    function miscSection() {
        var s = ""
        s += Config.windows.noCsd ? "prefer-no-csd\n" : ""
        s += "screenshot-path "
             + q(root.picturesDir() + "/Screenshots/%Y-%m-%d %H-%M-%S.png") + "\n"
        s += "\ncursor {\n    hide-when-typing\n}\n"
        s += "\nhotkey-overlay {\n    skip-at-startup\n}\n"
        return s
    }

    // All four numbers that decide what the glass looks like, in one place.
    //
    // ⚠️ Writing only `passes` did NOT mean the rest were switched off — niri
    // ships defaults (passes 3, offset 3, noise 0.02, saturation 1.5) and a
    // partial block leaves them standing. So this is not "turning on" three
    // effects; it is taking three numbers that were being decided elsewhere and
    // putting them where they can be seen and changed.
    //
    // Order matters when tuning: `offset` is free and `passes` is not.
    function blurSection() {
        // look.profile "minimal" is the one switch that turns the expensive
        // things off everywhere at once, rather than a setting per effect.
        var L = Config.look
        if (L.profile === "minimal" || !L.blur)
            return "blur {\n    off\n}\n"
        var s = "blur {\n"
        s += "    passes " + L.blurPasses + "\n"
        s += "    offset " + L.blurOffset + "\n"
        s += "    noise " + L.blurNoise + "\n"
        s += "    saturation " + L.blurSaturation + "\n"
        s += "}\n"
        return s
    }

    function workspacesSection() {
        var w = Config.workspaces
        var s = ""
        for (var i = 0; i < w.length; i++)
            s += "workspace " + q(w[i]) + "\n"
        return s
    }

    // ------------------------------------------------------------ animations
    // niri's own motion, on the shell's clock.
    //
    // Without this the compositor animates to its defaults — springs, and
    // ease-out-expo at 150 ms — while the island moves at 120/200/320 ms with a
    // soft curve. Two rhythms on one screen is exactly the "everything looks
    // like one system" promise coming apart, and it is the kind of difference
    // people feel without being able to name.
    //
    // ⚠️ Durations, not springs. A spring overshoots by definition, and the
    // brief rules overshoot out: fluid, not springy.
    function animationsSection() {
        if (Config.look.profile === "minimal") {
            // One line, and every animation in the compositor stops. This is the
            // switch to reach for on a slow machine.
            return "animations {\n    off\n}\n"
        }
        var fast = Theme.durFast, base = Theme.durBase, slow = Theme.durSlow
        function anim(name, ms) {
            return "    " + name + " {\n" +
                   "        duration-ms " + ms + "\n" +
                   "        curve \"ease-out-cubic\"\n" +
                   "    }\n"
        }
        var s = "animations {\n"
        s += anim("workspace-switch", base)
        s += anim("window-open", base)
        s += anim("window-close", fast)
        s += anim("horizontal-view-movement", base)
        s += anim("window-movement", base)
        s += anim("window-resize", base)
        s += anim("config-notification-open-close", slow)
        s += anim("overview-open-close", base)
        s += "}\n"
        return s
    }

    // ------------------------------------------------------------- rules
    function windowRules() {
        var L = Config.look
        var s = "window-rule {\n"
        s += "    geometry-corner-radius " + L.rounding + "\n"
        s += "    clip-to-geometry true\n"
        s += "}\n"
        // ⚠️ `opacityActive` HAD NO READER. Only the inactive rule was ever
        // written, so the key sat in shell.json doing nothing and every focused
        // window was fully opaque — reported as "the slight transparency is
        // missing in all the windows". A key with no reader is the same fault
        // this project has now found five times.
        //
        // ⚠️ And the honest part: compositor opacity fades the TEXT as well,
        // unlike kitty's own background_opacity, which only opens the
        // background. That is why the default is 0.95 and not lower.
        if (L.opacityActive < 1.0) {
            s += "\nwindow-rule {\n"
            s += "    match is-active=true\n"
            s += "    opacity " + L.opacityActive + "\n"
            s += "}\n"
        }
        if (L.opacityInactive < 1.0) {
            s += "\nwindow-rule {\n"
            s += "    match is-active=false\n"
            s += "    opacity " + L.opacityInactive + "\n"
            s += "}\n"
        }
        var fl = Config.windows.floating
        for (var i = 0; i < fl.length; i++) {
            s += "\nwindow-rule {\n"
            s += "    match app-id=" + q("^" + fl[i] + "$") + "\n"
            s += "    open-floating true\n"
            s += "}\n"
        }
        // Blur behind the windows that are translucent enough to show it.
        var bw = Config.windows.blurred
        for (var b = 0; b < bw.length; b++) {
            s += "\nwindow-rule {\n"
            s += "    match app-id=" + q("^" + bw[b] + "$") + "\n"
            s += "    background-effect {\n        blur true\n    }\n"
            s += "}\n"
        }

        var bl = Config.windows.blockFromScreencast
        for (var j = 0; j < bl.length; j++) {
            s += "\nwindow-rule {\n"
            s += "    match app-id=" + q("^" + bl[j] + "$") + "\n"
            s += "    block-out-from \"screencast\"\n"
            s += "}\n"
        }
        return s
    }

    function layerRules() {
        // The namespace is a public interface: the shell's layer surfaces are
        // named buchhwin-* and these rules match them. Renaming one later
        // silently drops its effects, so they do not get renamed.
        //
        // ⚠️ TWO THINGS NIRI'S DOCS SAY THAT DECIDE THIS WHOLE FUNCTION:
        //
        // 1. "niri has no way of knowing about invisible margins, and will draw
        //    the shadow behind the entire surface." Blur behaves the same. So a
        //    surface with a transparent border gets a blurred, colour-fringed
        //    halo — which is exactly what "the colours bug out around the
        //    notch" turned out to be. Our surfaces are sized to what they draw.
        //
        // 2. "Layer surface shadows always need to be enabled with a layer
        //    rule" — the `shadow` block in the layout section does NOT reach
        //    them. Which is why the shell's own surfaces had no shadow at all
        //    while every window did.
        var L = Config.look
        var s = ""

        function surface(ns, radius, blur) {
            var r = "layer-rule {\n"
            r += "    match namespace=" + q("^" + ns + "$") + "\n"
            r += "    geometry-corner-radius " + radius + "\n"
            if (Theme.shadows) {
                r += "    shadow {\n        on\n"
                r += "        softness " + L.shadowSoftness + "\n"
                r += "        spread " + L.shadowSpread + "\n"
                r += "        offset x=0 y=" + L.shadowOffsetY + "\n"
                r += "    }\n"
            }
            if (blur) {
                r += "    background-effect {\n        blur true\n    }\n"
            }
            r += "}\n"
            return r
        }

        var blurOn = !(L.profile === "minimal" || !L.blur)

        // ⚠️ THE RADIUS HERE MUST BE THE RADIUS THE SURFACE DRAWS, and getting
        // that wrong is what "the corners of all the panels are a weird red"
        // was. It used to pass `L.rounding` for every one of them, which is the
        // BASE from which the radii are derived — the panes actually draw
        // `Theme.radiusLg`, and with rounding 16 that is 21.
        //
        // Those five pixels are not cosmetic. `background-effect` belongs to the
        // SURFACE, not to the pane painted on it, and niri clips the blur to
        // this radius. A 16-radius blur under a 21-radius pane leaves a crescent
        // at every corner where the blurred wallpaper is shown RAW — and raw
        // means through `blur { saturation … }`. Measured on the running VM with
        // the panel open: the panel interior is rgb(44,44,42), r−b = +2, and the
        // crescent is rgb(144,46,6), r−b = +138 — MORE saturated than the
        // wallpaper below the panel (+81). Four red arcs, one per corner, on
        // every surface with blur.
        //
        // So each namespace is handed the number its own painter uses. If a
        // surface ever changes what it draws, this has to follow — which is why
        // tests/niri-config.sh now checks the pairing rather than trusting it.
        var paneRadius = Theme.radiusLg          // GlassPane in overlay/launcher/toast
        var notchRadius = Config.notch.cornerRadius  // Silhouette's own corners

        // ⚠️ NO BLUR BEHIND THE NOTCH. It is near-black and opaque, so there was
        // never anything to see through it — the blur bought nothing and cost
        // both the halo and a full-screen GPU read per frame. Blur belongs where
        // something is actually translucent.
        s += surface("buchhwin-notch", notchRadius, false)
        s += "\n" + surface("buchhwin-overlay", paneRadius, blurOn)
        s += "\n" + surface("buchhwin-bar", 0, blurOn)
        // The toasts are translucent panes like the pages, so they get the same
        // treatment. Their surface is sized to the cards, so the shadow niri
        // draws behind the whole thing is the cards' shadow.
        s += "\n" + surface("buchhwin-toast", paneRadius, blurOn)
        // The launcher is a translucent pane like the pages, and the only one
        // that sits in the middle of the screen — which is exactly where a
        // missing blur rule would be most obvious, with the wallpaper showing
        // through sharp behind a list of programs.
        s += "\n" + surface("buchhwin-launcher", paneRadius, blurOn)
        // The pill beside the notch. Same treatment as the notch itself and
        // for the same reason: it is a small opaque shape, so there is nothing
        // to see through it and a blur pass behind it would be paid for and
        // then covered up.
        return s
    }

    // ------------------------------------------------------------------ binds
    // Actions that take a bare (unquoted) number rather than a string.
    readonly property var numericActions: ["focus-workspace", "move-window-to-workspace",
                                           "move-column-to-workspace"]

    function bindLine(b) {
        var key = String(b.key)
        var action = String(b.action)
        var arg = b.arg === undefined || b.arg === null ? "" : String(b.arg)

        var body = ""
        if (action === "spawn") {
            // One string per argument. `spawn "kitty -e fish"` makes niri look
            // for a binary called "kitty -e fish"; the error message does not
            // mention the real cause, so this is worth getting right once.
            var argv = Config.program(arg)
            if (!argv.length)
                return ""   // no program configured: drop the key rather than
                            // bind it to something that quietly does nothing
            body = "spawn" + argList(argv)
        } else if (action === "spawn-sh") {
            if (!arg.length) return ""
            body = "spawn-sh " + q(arg)
        } else if (arg.length) {
            var numeric = numericActions.indexOf(action) >= 0 && /^[0-9]+$/.test(arg)
            body = action + " " + (numeric ? arg : q(arg))
        } else {
            body = action
        }

        var props = ""
        if (b.allowWhenLocked === true) props += " allow-when-locked=true"
        if (b.repeat === false) props += " repeat=false"
        if (typeof b.cooldownMs === "number") props += " cooldown-ms=" + b.cooldownMs
        if (b.desc) props += " hotkey-overlay-title=" + q(b.desc)

        return "    " + key + props + " { " + body + "; }\n"
    }

    function bindsSection() {
        var s = "binds {\n"
        var binds = Config.binds
        var seen = ({})
        var dropped = 0
        for (var i = 0; i < binds.length; i++) {
            var b = binds[i]
            // A duplicate key is a hard parse error in niri, and a config that
            // does not load means a desktop with no keys at all. Catch it here,
            // where we can say which key, instead of there.
            if (seen[b.key]) {
                note("  ⚠ duplicate key dropped: " + b.key)
                dropped++
                continue
            }
            var line = bindLine(b)
            if (!line.length) { dropped++; continue }
            seen[b.key] = true
            s += line
        }
        // Workspace switching, generated rather than typed out ten times.
        for (var n = 1; n <= 9; n++) {
            s += "    Mod+" + n + " { focus-workspace " + n + "; }\n"
            s += "    Mod+Shift+" + n + " { move-window-to-workspace " + n + "; }\n"
        }
        s += "}\n"
        if (dropped)
            note("  " + dropped + " binding(s) skipped (no program configured or duplicate)")
        return s
    }

    // -------------------------------------------------------------- autostart
    function autostartSection() {
        // NOT the shell and NOT the clipboard watcher. Both are systemd user
        // units bound to graphical-session.target already; listing them here
        // would start a second copy of each. This is the exact mistake in
        // Fedora's shipped niri config, which spawns waybar at startup.
        var a = Config.autostart
        if (!a.length)
            return "// Nothing to spawn: the shell and the clipboard watcher are\n" +
                   "// systemd user units, not startup commands. Adding them here\n" +
                   "// would run a second copy of each.\n"
        // ⚠️ NOT `spawn-sh` — that is the name of a BIND action. At the top
        // level the node is `spawn-sh-at-startup`, and niri rejects the other
        // spelling outright ("unexpected node `spawn-sh`"), which means no
        // config at all and therefore a desktop with no keybindings.
        var s = ""
        for (var i = 0; i < a.length; i++)
            s += "spawn-sh-at-startup " + q(a[i]) + "\n"
        return s
    }

    // ------------------------------------------------------------------ build
    function buildConfig() {
        var parts = []
        parts.push(header)
        parts.push(inputSection())
        parts.push(outputsSection())
        parts.push(layoutSection())
        parts.push(animationsSection())
        // AFTER layout, on purpose: an include overrides what came before it,
        // so the colours have to be read after the structure that they tint.
        parts.push("// Colours, written by tools/render.qml on every palette change.\n" +
                   "// optional=true: a fresh checkout has no colours yet and that must\n" +
                   "// not stop niri from starting.\n" +
                   "include optional=true " + q("~/.config/niri/colors.kdl") + "\n")
        parts.push(miscSection())
        parts.push(environmentSection())
        parts.push(blurSection())
        parts.push(workspacesSection())
        parts.push(windowRules())
        parts.push(layerRules())
        parts.push(bindsSection())
        parts.push(autostartSection())
        return parts.join("\n")
    }

    // ------------------------------------------------- desktop file overrides
    //
    // ⚠️ 43 TO 100 SECONDS, MEASURED, and this is what fixes it. Brave on a
    // Wayland-only session takes that long to put a window on screen, because
    // it probes for X11 first and waits for that to fail. Timed from exec to
    // the window appearing, twice each:
    //
    //     no flag                     57 s  and  100 s
    //     --ozone-platform-hint=auto  42.9 s and  43.1 s
    //     --ozone-platform=wayland     1.5 s and   1.4 s
    //
    // The recommended `hint=auto` is almost no help — it is the explicit one
    // that skips the probe. So the launcher gets the explicit one.
    //
    // ⚠️ THE TRADE, SAID OUT LOUD: `=wayland` means Brave will not start on an
    // X11 session at all. This desktop is Wayland-only by design and by plan,
    // and a browser that takes a minute and a half to open is not a browser
    // anybody keeps. Somebody who needs X11 deletes the override — it is one
    // file in ~/.local/share/applications.
    //
    // ⚠️ THE ORIGINAL IS COPIED, NOT REBUILT. A user desktop file REPLACES the
    // system one rather than adding to it, so a hand-written one would quietly
    // drop every translated name and both right-click actions. This reads the
    // installed file and rewrites its Exec lines, which keeps all of it.
    readonly property var desktopOverrides: [
        { file: "brave-browser.desktop", flag: "--ozone-platform=wayland" }
    ]

    FileView { id: fSystemDesktop; blockLoading: true; printErrors: false }
    FileView { id: fUserDesktop; blockLoading: true; printErrors: false }

    function desktopOverride(source, flag) {
        var lines = source.split("\n")
        var out = []
        for (var i = 0; i < lines.length; i++) {
            var l = lines[i]
            if (l.indexOf("Exec=") === 0 && l.indexOf(flag) < 0) {
                // The flag goes after the binary and before any %U, or the
                // browser is handed its own flag as a file to open.
                var rest = l.substring(5)
                var sp = rest.indexOf(" ")
                l = sp < 0 ? "Exec=" + rest + " " + flag
                           : "Exec=" + rest.substring(0, sp) + " " + flag + rest.substring(sp)
            }
            out.push(l)
        }
        return out.join("\n")
    }

    function writeDesktopOverrides() {
        var home = Quickshell.env("HOME") || "~"
        var userDir = (Quickshell.env("XDG_DATA_HOME") || home + "/.local/share")
                      + "/applications/"
        for (var i = 0; i < root.desktopOverrides.length; i++) {
            var o = root.desktopOverrides[i]
            fSystemDesktop.path = "/usr/share/applications/" + o.file
            var src = fSystemDesktop.text()
            if (!src || src.length === 0) {
                note("  " + o.file + ": not installed, nothing to override")
                continue
            }
            write(fUserDesktop, userDir + o.file,
                  root.desktopOverride(src, o.flag), o.file)
        }
    }

    // blockLoading so that write() can compare against what is already on disk
    // in the same statement. printErrors off: "the file is not there yet" is
    // the normal case on a first run, not a fault worth shouting about.
    FileView { id: fConfig; blockLoading: true; printErrors: false }
    FileView { id: fEnv; blockLoading: true; printErrors: false }
    FileView { id: log; path: "/tmp/buchhwin-niri.log" }

    // ⚠️ WHERE SCREENSHOTS GO IS NOT OURS TO INVENT. This used to write
    // "~/Bilder/Screenshots" — the German name — straight into the generated
    // config. On any machine that is not set to German that is a folder nobody
    // has, created on first screenshot, and never looked in. The repository is
    // public, so most of the people it lands on are exactly those machines.
    //
    // xdg-user-dirs is the answer everyone else uses, and it is a plain file:
    // XDG_PICTURES_DIR="$HOME/Bilder". Absent on minimal installs — the VM this
    // was tested on has no such file — so the fallback matters as much as the
    // lookup, and the fallback is the XDG default, not a translation.
    FileView { id: fUserDirs; blockLoading: true; printErrors: false
               path: root.cfg + "/user-dirs.dirs" }

    function picturesDir() {
        var txt = fUserDirs.text()
        if (txt && txt.length) {
            var m = txt.match(/^\s*XDG_PICTURES_DIR\s*=\s*"([^"]*)"/m)
            if (m && m[1].length) {
                // The file writes $HOME literally; it is not a shell here.
                return m[1].replace("$HOME", Quickshell.env("HOME") || "~")
            }
        }
        return (Quickshell.env("HOME") || "~") + "/Pictures"
    }

    WaitFor {
        condition: Config.settled

        onTimedOut: {
            note("buchhwin niri — ABORT: the configuration never settled")
            Qt.callLater(Qt.quit)
        }

        onReady: {
            note("buchhwin niri — generating from shell.json (version " + Config.version + ")")
            write(fConfig, root.cfg + "/niri/config.kdl", buildConfig(), "niri config")
            write(fEnv, root.cfg + "/environment.d/50-buchhwin.conf",
                  environmentD(), "environment.d")
            root.writeDesktopOverrides()
            note("done: " + written + " written, " + unchanged + " unchanged")
            Qt.callLater(Qt.quit)
        }
    }
}
