// The renderer: writes every foreign application's colours, fonts and radii
// from the same tokens the shell draws itself with.
//
//   BUCHHWIN_TOOL=render QT_QPA_PLATFORM=offscreen qs -p shell
//
// This is what makes "change the palette, everything follows" true rather than
// aspirational. It runs in three situations and is the SAME code every time:
//
//   * during installation, before any session exists (headless)
//   * whenever the palette or a look setting changes (from the running shell)
//   * from `bhctl theme`, as a repair
//
// There is deliberately no template engine and no second renderer in bash.
// One writer, one set of tokens, no drift.
//
// Note the GTK caveat, which is written into the generated files too: setting
// gtk-decoration-layout to ":" removes the three window buttons, but a
// libadwaita headerbar is application CONTENT and stays. We remove the
// buttons, not the bar, and we say so instead of pretending.

import QtQuick
import Quickshell
import Quickshell.Io
import "../theme"
import "../config"
import "../common"

Scope {
    id: root

    readonly property string home: Quickshell.env("HOME")
    readonly property string cfg: Quickshell.env("XDG_CONFIG_HOME") || (home + "/.config")

    property string report: ""
    property int written: 0

    function note(s) { report += s + "\n"; log.setText(report) }

    // Every file goes through here so that "what did the renderer touch" is a
    // single list, and so a failure is reported rather than swallowed.
    function write(view, path, text, label) {
        view.path = path
        view.setText(text)
        written++
        note("  wrote  " + label + "  ->  " + path)
    }

    readonly property string header:
        "/* Generated by buchhwin from palette '" + Scheme.name + "'.\n" +
        " * Do not edit: every write of this file is overwritten on the next\n" +
        " * palette or look change. Change the palette instead.\n" +
        " */\n"

    readonly property string headerHash:
        "# Generated by buchhwin from palette '" + Scheme.name + "'.\n" +
        "# Do not edit — regenerated on every palette or look change.\n"

    // ------------------------------------------------------------------ GTK 3
    function gtk3Css() {
        return header +
            "@define-color theme_bg_color " + Theme.hex(Theme.bg) + ";\n" +
            "@define-color theme_fg_color " + Theme.hex(Theme.fg) + ";\n" +
            "@define-color theme_base_color " + Theme.hex(Theme.surface) + ";\n" +
            "@define-color theme_text_color " + Theme.hex(Theme.fg) + ";\n" +
            "@define-color theme_selected_bg_color " + Theme.hex(Theme.accent) + ";\n" +
            "@define-color theme_selected_fg_color " + Theme.hex(Theme.accentFg) + ";\n" +
            "@define-color insensitive_bg_color " + Theme.hex(Theme.bgDim) + ";\n" +
            "@define-color insensitive_fg_color " + Theme.hex(Theme.fgDisabled) + ";\n" +
            "@define-color borders " + Theme.hex(Theme.outline) + ";\n" +
            "@define-color warning_color " + Theme.hex(Theme.warn) + ";\n" +
            "@define-color error_color " + Theme.hex(Theme.error) + ";\n" +
            "@define-color success_color " + Theme.hex(Theme.ok) + ";\n" +
            "@define-color accent_color " + Theme.hex(Theme.accent) + ";\n" +
            "@define-color accent_fg_color " + Theme.hex(Theme.accentFg) + ";\n" +
            "\n/* Corners follow look.rounding, like every other surface. */\n" +
            "menu, .menu, popover, .popup, tooltip { border-radius: " + Theme.radiusMd + "px; }\n" +
            "button { border-radius: " + Theme.radiusSm + "px; }\n"
    }

    // ------------------------------------------------------------------ GTK 4
    function gtk4Css() {
        return header +
            "@define-color window_bg_color " + Theme.hex(Theme.bg) + ";\n" +
            "@define-color window_fg_color " + Theme.hex(Theme.fg) + ";\n" +
            "@define-color view_bg_color " + Theme.hex(Theme.bgDim) + ";\n" +
            "@define-color view_fg_color " + Theme.hex(Theme.fg) + ";\n" +
            "@define-color headerbar_bg_color " + Theme.hex(Theme.surface) + ";\n" +
            "@define-color headerbar_fg_color " + Theme.hex(Theme.fg) + ";\n" +
            "@define-color popover_bg_color " + Theme.hex(Theme.surface) + ";\n" +
            "@define-color popover_fg_color " + Theme.hex(Theme.fg) + ";\n" +
            "@define-color card_bg_color " + Theme.hex(Theme.surface) + ";\n" +
            "@define-color card_fg_color " + Theme.hex(Theme.fg) + ";\n" +
            "@define-color sidebar_bg_color " + Theme.hex(Theme.bgDim) + ";\n" +
            "@define-color sidebar_fg_color " + Theme.hex(Theme.fg) + ";\n" +
            "@define-color dialog_bg_color " + Theme.hex(Theme.surface) + ";\n" +
            "@define-color dialog_fg_color " + Theme.hex(Theme.fg) + ";\n" +
            "@define-color accent_bg_color " + Theme.hex(Theme.accent) + ";\n" +
            "@define-color accent_fg_color " + Theme.hex(Theme.accentFg) + ";\n" +
            "@define-color accent_color " + Theme.hex(Theme.accent) + ";\n" +
            "@define-color destructive_bg_color " + Theme.hex(Theme.error) + ";\n" +
            "@define-color destructive_fg_color " + Theme.hex(Theme.errorFg) + ";\n" +
            "@define-color success_color " + Theme.hex(Theme.ok) + ";\n" +
            "@define-color warning_color " + Theme.hex(Theme.warn) + ";\n" +
            "@define-color error_color " + Theme.hex(Theme.error) + ";\n" +
            "@define-color borders " + Theme.hex(Theme.outline) + ";\n" +
            "\nwindow, popover > contents, .card { border-radius: " + Theme.radiusMd + "px; }\n" +
            "button { border-radius: " + Theme.radiusSm + "px; }\n"
    }

    function gtkSettings() {
        // ":" means: no window buttons on either side.
        // Honest note, repeated in the file itself: this removes the three
        // buttons. A libadwaita headerbar is content, not decoration, and stays.
        return headerHash +
            "# gtk-decoration-layout=\":\" removes the minimise/maximise/close\n" +
            "# buttons. It does NOT remove a libadwaita headerbar — that is part\n" +
            "# of the application's own layout and no setting can take it away.\n" +
            "[Settings]\n" +
            "gtk-application-prefer-dark-theme=" + (Theme.dark ? 1 : 0) + "\n" +
            "gtk-theme-name=" + (Theme.dark ? "adw-gtk3-dark" : "adw-gtk3") + "\n" +
            "gtk-icon-theme-name=" + (Theme.dark ? "Papirus-Dark" : "Papirus-Light") + "\n" +
            "gtk-font-name=" + Theme.fontUi + " " + Theme.fontSizePt + "\n" +
            "gtk-decoration-layout=:\n" +
            "gtk-xft-antialias=1\n" +
            "gtk-xft-hinting=1\n" +
            "gtk-xft-hintstyle=hintslight\n" +
            "gtk-xft-rgba=rgb\n"
    }

    // ------------------------------------------------------------------ kitty
    function kittyTheme() {
        return headerHash +
            "foreground " + Theme.hex(Theme.fg) + "\n" +
            "background " + Theme.hex(Theme.bg) + "\n" +
            "selection_foreground " + Theme.hex(Theme.accentFg) + "\n" +
            "selection_background " + Theme.hex(Theme.accent) + "\n" +
            "cursor " + Theme.hex(Theme.accent) + "\n" +
            "cursor_text_color " + Theme.hex(Theme.accentFg) + "\n" +
            "url_color " + Theme.hex(Theme.info) + "\n" +
            "active_border_color " + Theme.hex(Theme.accent) + "\n" +
            "inactive_border_color " + Theme.hex(Theme.outline) + "\n" +
            "active_tab_foreground " + Theme.hex(Theme.accentFg) + "\n" +
            "active_tab_background " + Theme.hex(Theme.accent) + "\n" +
            "inactive_tab_foreground " + Theme.hex(Theme.fgDim) + "\n" +
            "inactive_tab_background " + Theme.hex(Theme.surface) + "\n" +
            "font_family " + Theme.fontMono + "\n" +
            "font_size " + Theme.fontSizePt + "\n" +
            "color0 " + Theme.hex(Theme.bgDeep) + "\n" +
            "color8 " + Theme.hex(Theme.overlay) + "\n" +
            "color1 " + Theme.hex(Theme.error) + "\n" +
            "color9 " + Theme.hex(Theme.error) + "\n" +
            "color2 " + Theme.hex(Theme.ok) + "\n" +
            "color10 " + Theme.hex(Theme.ok) + "\n" +
            "color3 " + Theme.hex(Theme.warn) + "\n" +
            "color11 " + Theme.hex(Theme.warn) + "\n" +
            "color4 " + Theme.hex(Theme.info) + "\n" +
            "color12 " + Theme.hex(Theme.info) + "\n" +
            "color5 " + Theme.hex(Scheme.color("mauve")) + "\n" +
            "color13 " + Theme.hex(Scheme.color("mauve")) + "\n" +
            "color6 " + Theme.hex(Scheme.color("teal")) + "\n" +
            "color14 " + Theme.hex(Scheme.color("teal")) + "\n" +
            "color7 " + Theme.hex(Theme.fgMuted) + "\n" +
            "color15 " + Theme.hex(Theme.fg) + "\n"
    }

    // ------------------------------------------------------------------- niri
    // COLOURS ONLY. This file is `include`d by the generated config.kdl, and
    // the split is what lets a palette change leave the keybindings alone.
    //
    // ⚠️ Two rules, both from niri's own documentation and both easy to break:
    //
    //  * No `on`, no `off`, no `width`, no `gaps` here. Whether a border exists
    //    is a look setting and belongs to tools/niri.qml. Worse, the meaning
    //    differs by file: "writing layout { border {} } in an included config
    //    does nothing… the same in the main config will ENABLE the border".
    //    Deciding visibility from here would mean deciding it differently
    //    depending on which file happened to be read.
    //
    //  * An include overrides what came before it, so config.kdl places this
    //    include after its own layout block. Sections merge property by
    //    property, so setting only colours leaves gaps and width untouched.
    function niriColours() {
        return headerHash.replace(/^#/gm, "//") +
            "// Colours only — see tools/render.qml. Structure lives in config.kdl.\n" +
            "layout {\n" +
            "    background-color \"" + Theme.hex(Theme.bgDeep) + "\"\n" +
            "    border {\n" +
            "        active-color \"" + Theme.hex(Theme.accent) + "\"\n" +
            "        inactive-color \"" + Theme.hex(Theme.outline) + "\"\n" +
            "        urgent-color \"" + Theme.hex(Theme.error) + "\"\n" +
            "    }\n" +
            "    focus-ring {\n" +
            "        active-color \"" + Theme.hex(Theme.accent) + "\"\n" +
            "        inactive-color \"" + Theme.hex(Theme.outline) + "\"\n" +
            "        urgent-color \"" + Theme.hex(Theme.error) + "\"\n" +
            "    }\n" +
            "    shadow {\n" +
            "        color \"" + Theme.hex(Theme.bgDeep) + "b0\"\n" +
            "    }\n" +
            "    insert-hint {\n" +
            "        color \"" + Theme.hex(Theme.accent) + "80\"\n" +
            "    }\n" +
            "    tab-indicator {\n" +
            "        active-color \"" + Theme.hex(Theme.accent) + "\"\n" +
            "        inactive-color \"" + Theme.hex(Theme.outline) + "\"\n" +
            "        urgent-color \"" + Theme.hex(Theme.error) + "\"\n" +
            "    }\n" +
            "}\n" +
            "\noverview {\n" +
            "    backdrop-color \"" + Theme.hex(Theme.bgDim) + "\"\n" +
            "}\n"
    }

    // ------------------------------------------------------------------- Qt
    function qtColors() {
        function q(c) { return Theme.hex(c) }
        return headerHash +
            "[ColorScheme]\n" +
            "active_colors=" + [q(Theme.fg), q(Theme.surface), q(Theme.surfaceHigh),
                                q(Theme.surface), q(Theme.bgDim), q(Theme.bg),
                                q(Theme.fg), q(Theme.fg), q(Theme.fg), q(Theme.bg),
                                q(Theme.bg), q(Theme.bgDeep), q(Theme.accent),
                                q(Theme.accentFg), q(Theme.info), q(Theme.accentAlt),
                                q(Theme.surface), q(Theme.fg), q(Theme.bgDim),
                                q(Theme.fg), q(Theme.fgDisabled)].join(", ") + "\n"
    }

    FileView { id: f1 }
    FileView { id: f2 }
    FileView { id: f3 }
    FileView { id: f4 }
    FileView { id: f5 }
    FileView { id: f6 }
    FileView { id: f7 }
    FileView { id: log; path: "/tmp/buchhwin-render.log" }

    // Wait for the palette to actually be there. The previous fixed 700 ms
    // timer looked like it was doing this and was not: it touched Scheme for
    // the first time inside itself, so the palette had not begun loading when
    // `ready` was tested. See WaitFor.qml.
    WaitFor {
        condition: Config.settled && Scheme.ready

        onTimedOut: {
            note("buchhwin render — ABORT")
            note("  the palette did not load; refusing to write fallback colours")
            note("  " + (Scheme.failure.length ? Scheme.failure : "no reason reported"))
            Qt.callLater(Qt.quit)
        }

        onReady: {
            note("buchhwin render — palette " + Scheme.name +
                 " (" + Scheme.displayName + "), accent " + Config.theme.accent)

            write(f1, root.cfg + "/gtk-3.0/gtk.css",      gtk3Css(),    "gtk3 colours")
            write(f2, root.cfg + "/gtk-3.0/settings.ini", gtkSettings(), "gtk3 settings")
            write(f3, root.cfg + "/gtk-4.0/gtk.css",      gtk4Css(),    "gtk4 colours")
            write(f4, root.cfg + "/gtk-4.0/settings.ini", gtkSettings(), "gtk4 settings")
            write(f5, root.cfg + "/kitty/theme.conf",     kittyTheme(), "kitty")
            write(f6, root.cfg + "/niri/colors.kdl",      niriColours(), "niri colours")
            write(f7, root.cfg + "/qt6ct/colors/buchhwin.conf", qtColors(), "qt6ct")

            note("done: " + written + " files")
            Qt.callLater(Qt.quit)
        }
    }
}
